site_name: Holly Lesmeister
nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Interview Process: interview-process.md
  - Drafting the Biography: drafting-bio.md

img: site/assets/images/Online-Interview.jpeg


theme: material
